### ISSUE TITLE
--meta: command not found in uga v2.0b3

### ISSUE THREAD

**Issue by shirley0818** [rmkoesterer/uga#20]
## With "uga v2.0b3 (c) 2015", I got a error message "./high.enriched.sh: line 30: --meta: command not found". However, everything is fine with uga2.0b3 two months ago.  Please find below an example code. Thanks,
# !/bin/bash

uga snvgroup \
..
...
--meta meta ea+hi

**Comment by rmkoesterer** [comment]
Hi,

I believe that the error you are getting is not related to uga. It looks like bash thinks that line 30 of your script is the start of a new command. You might be missing a '\' at the end of the previous line.

Also, uga v2.0b3 is locked and code for that version will never change.

**Comment by shirley0818** [comment]
Thanks a lot for your quick response. Yes. You are right. I missed a "\" at the end of the previous line. Now it works fine. 

Thanks,
