### ISSUE TITLE
output single variant result in gene-based test

### ISSUE THREAD

**Issue by shirley0818** [rmkoesterer/uga#21]
Using the gene-based pipeline "uga snvgroup", the output fine includes pvalue, pvalue_min, , cmac and nsnps. I am wondering whether the pipeline can output snp_id, cmac, pvalue, etc for each SNP included in the gene-based test for each gene. 

Many thanks,
Xiaoling

**Comment by rmkoesterer** [comment]
Hi Xiaoling,

Unfortunately seqMeta does not output single variant results along with the gene based results. I believe the only way for you to do that is to run 'uga snv' and use '--score', which is seqMeta's singleSnpMeta test, then merge them manually.

Ryan

**Comment by shirley0818** [comment]
Hi Ryan,

Thanks for your response. In fact, I checked the results from running "uga snv" -- score. The problem for score test is that for variants with mac <=1 (i.e., 0 count in cases or control group), the result was set to NA.
Please check the following example:

id                                 geen n    mac
19:35832827:T:TGG     CD22  5424    0

>zcat wes.r3.all.score.enriched.ea.gc.gz | grep "19:35832827"

chr     pos     id      a1      a2      filter  callrate        rsq     hwe     n       mac     freq    freq.case       freq.ctrl       err     nmiss   ntotal  effect  stderr  or      p
19      35832827        19:35832827:T:TGG       T       TGG     1100    1       NA      1       5424    0       1       1       1       NA  NA       NA      NA      NA      NA      NA


Xiaoling Zhang, Ph.D.
Assistant Professor of Medicine and Biostatistics
Section of Biomedical Genetics
Boston University School of Medicine
72 East Concord Street, Room E223
Boston, MA  02118-2526
Tel:  617-638-5040
http://www.bumc.bu.edu/genetics
________________________________

**Comment by rmkoesterer** [comment]
Perhaps I don't understand what you are saying. That SNP is monomorphic, so it can't be tested, which explains the missing values (NA's).

**Comment by shirley0818** [comment]
Sorry that I gave you an bad example.

An example is for a SNP with 100 risk Alleles in cases, but 0 risk allele in control. The single score test will not test it and therefore output NA missing values.

Best,

Xiaoling Zhang, Ph.D.
Assistant Professor of Medicine and Biostatistics
Section of Biomedical Genetics
Boston University School of Medicine
72 East Concord Street, Room E223
Boston, MA  02118-2526
Tel:  617-638-5040
http://www.bumc.bu.edu/genetics
________________________________

**Comment by rmkoesterer** [comment]
Do you know why it isn't being test? Is there a frequency threshold being used? You can set basically any of the parameters that are available in seqMeta. If you don't set them, then the defaults are used as defined in seqMeta.

**Comment by shirley0818** [comment]
I will check the parameters first and then let you if I have further questions:)

Many thanks and have a nice weekend,
Xiaoling
---

Xiaoling Zhang, Ph.D.
Assistant Professor of Medicine and Biostatistics
Section of Biomedical Genetics
Boston University School of Medicine
72 East Concord Street, Room E223
Boston, MA  02118-2526
Tel:  617-638-5040
http://www.bumc.bu.edu/genetics
________________________________

**Comment by shirley0818** [comment]
Hi Ryan,

Sorry to bother you again. Based on your suggestions, I rerun uga by setting “--mac 1” for the single variant analysis since I would like to generate results for any variant included in the gene-based analysis. But in our case, for variant with mac = 1 (e.g, 19:35826945:CT:C), the result is set to NA

>zcat wes.r3.all.score.enriched_mac1.ea.gz | grep "19:35826945:CT:C"
19      35826945        19:35826945:CT:C        CT      C       1000    0.99668 NA      1       5406    1       0.99991 0.999   1       NA  NA       NA      NA      NA      NA      NA

However, the group at University of Washington, their pipeline generates p value for variant with mac = 1. Could you let me know whether I have missed anything regarding “uga”?

Attached please find the results of UW (please check Slide 4). Below is “score.enriched.mac1.sh” for your reference. Many thanks for your help,  Xiaoling

---------------
#!/bin/bash
uga snv \
--replace \
--out wes.r3.all.score.enriched_mac1 \
--fid FAM_ID \
--iid IND_ID \
--patid FAT_ID \
--matid MOT_ID \
--sex Sex \
--male 0 \
--mac 1 \
--case 1 \
--ctrl 0 \
--male 0 \
--female 1 \
--qsub "-P casa -N wes.r3.all.score.enriched -l mem_free=1g -pe omp 4" \
--split-n 200 \
--cpus 4 \
--vcf /restricted/projectnb/casa/_wes/_consensus_r3snv_plus_indel_vcf/snv_plus_indel.vcf.gz \
--tag ea \
--score \
--pheno AD \
--covars "factor(Sex)+Age+PC1+PC2+PC3+PC4+PC5+PC6+PC7+PC8+PC9+PC10" \
--ped  ../r3.wes.ea.droped.5424.enriched_vs_ctrl.new.ped \
--tag hi \
--score \
--pheno AD \
--covars "factor(Sex)+Age+PC1+PC2+PC3" \
--ped ../r3.wes.hisp.droped.349.enriched_vs_ctrl.new.ped

**Comment by rmkoesterer** [comment]
Hi Xiaoling,
I originally set up UGA to work with other R packages (geepack, etc) for single variant tests. Some of those packages would fail to return a result if in a case/control analysis the frequency in cases or controls was 0 or 1. It sounds like you discovered that seqMeta doesn't fail in that case. I can offer a quick fix for you to change the behavior of UGA. In the source code, find the file 'RunSnv.py'. On line 127 (i believe) you will find this line
'hwe_maf_thresh=cfg['models'][n]['hwe_maf'])'
Change that line to
'hwe_maf_thresh=cfg['models'][n]['hwe_maf'],no_mono=False)'
This will deactivate that filter, but may result in some tests other than the score test not working properly. 
After changing that file you'll need to reinstall UGA as described in the instructions.

**Comment by shirley0818** [comment]
Hi Ryan,

Thanks a lot for your quick response. I just tried your suggestions. It works. Thanks.

BTW, you said “This will deactivate that filter, but may result in some tests other than the score test not working properly.”. Does it mean I have to change this filter back to the default “no_mono=True” in the future for other tests?

Thanks again,
Xiaoling

**Comment by rmkoesterer** [comment]
The short answer is 'maybe'. You will know that this is a problem if you can't get analyses to finish when running another test. The job will just freeze on a call to the R function for the association test. I believe that it was the 'gee' function that allowed this to happen, but do not recall exactly. I will definitely change this whenever I get to an update of UGA in the future. I will just make that option conditional on the test being run.

Thanks for finding this issue and i'm glad the quick fix worked out for you.
,
Ryan

**Comment by shirley0818** [comment]
Thank you for your correct suggestion!

With an option conditional on the test would be great. Please let us know once your updated UGA becomes available.

Best,
Xiaoling

**Comment by rmkoesterer** [comment]
Fixed by adding --allow-mono option for SNV tests.
