### ISSUE TITLE
error when running "snvgroupplot"

### ISSUE THREAD

**Issue by shirley0818** [rmkoesterer/uga#25]
When running "uga snvgroupplot --file wes.release3.high.enriched/wes.release3.high.enriched.ea.filtered.gz --color --qq --qq-strat --mht", I got the following permission error message which I have never got before. Thanks. Xiaoling from BU

(uga_python2.7)[zhangxl@scc4 uga_snvgroup]$ uga snvgroupplot --file wes.release3.high.enriched/wes.release3.high.enriched.meta.filtered.gz --color --qq --qq-strat --mht

uga v2.0b3 (c) 2015 Ryan Koesterer   GNU General Public License v3

   This program is free software: you can redistribute it and/or
   modify it under the terms of the GNU General Public License as
   published by the Free Software Foundation, either version 3 of the
   License, or (at your option) any later version.

   This program is distributed in the hope that it will be useful, but
   WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
   General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with this program.  If not, see
   <http://www.gnu.org/licenses/>

active module: snvgroupplot
Traceback (most recent call last):
  File "/usr3/graduate/zhangxl/.conda/envs/uga_python2.7/bin/uga", line 9, in <module>
    load_entry_point('uga==2.0b3', 'console_scripts', 'uga')()
  File "/usr3/graduate/zhangxl/.conda/envs/uga_python2.7/lib/python2.7/site-packages/uga-2.0b3-py2.7-linux-x86_64.egg/uga/__main__.py", line 366, in main
    Process.interactive(qsub_wrapper, cmd, cfg['out'] + '.log')
  File "/usr3/graduate/zhangxl/.conda/envs/uga_python2.7/lib/python2.7/site-packages/uga-2.0b3-py2.7-linux-x86_64.egg/uga/Process.py", line 42, in interactive
    p = subprocess.Popen([submit,cmd], stdout=subprocess.PIPE, stderr=subprocess.STDOUT, bufsize=1)
  File "/usr3/graduate/zhangxl/.conda/envs/uga_python2.7/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr3/graduate/zhangxl/.conda/envs/uga_python2.7/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
**OSError: [Errno 13] Permission denied**

**Comment by rmkoesterer** [comment]
Hi Xiaoling,

Sorry about the delay, I haven't been working with UGA much lately, so haven't checked in. Your error is saying that you don't have appropriate permissions to read or execute a file. This is not a UGA error. It comes from the operating system. It appears that you are trying to include a file that you don't have permission to access, or it could be possible that your permissions have changed for the qsub wrapper script.

Ryan

**Comment by shirley0818** [comment]
Thanks Ryan for your response.  I just checked, I should have permission to access the file in the command as listed below:
(uga_python2.7)[zhangxl@scc4 uga_snvgroup]$ uga snvgroupplot --file wes.release3.high.enriched/wes.release3.high.enriched.meta.filtered.gz --color --qq --qq-strat --mht
[zhangxl@scc4 uga_snvgroup]$ ls -l wes.release3.high.enriched/*.gz
-rw-r--r-- 1 zhangxl casa  68151 Jan  3 12:53 wes.release3.high.enriched/wes.release3.high.enriched.ea.filtered.gz
-rw-r--r-- 1 zhangxl casa 379668 Jan  3 12:50 wes.release3.high.enriched/wes.release3.high.enriched.ea.gz
-rw-r--r-- 1 zhangxl casa  10424 Jan  3 12:53 wes.release3.high.enriched/wes.release3.high.enriched.hi.filtered.gz
-rw-r--r-- 1 zhangxl casa 283383 Jan  3 12:50 wes.release3.high.enriched/wes.release3.high.enriched.hi.gz
-rw-r--r-- 1 zhangxl casa  56281 Jan  3 12:53 wes.release3.high.enriched/wes.release3.high.enriched.meta.filtered.gz
-rw-r--r-- 1 zhangxl casa 296507 Jan  3 12:50 wes.release3.high.enriched/wes.release3.high.enriched.meta.gz

Many thanks,
Xiaoling

**Comment by rmkoesterer** [comment]
In the error, it appears to have a problem with running the qsub_wrapper, which in your version (2.0b3) should be pointing to the file /usr3/graduate/zhangxl/.conda/envs/uga_python2.7/lib/python2.7/site-packages/uga-2.0b3-py2.7-linux-x86_64.egg/uga/Qsub.py. You will need execute permissions on that file to run interactively. I would certainly recommend updating to the latest release, 2.0b5, since a number of issues were resolved and improvements have been made since 2.0b3. One improvement that was made  moved the Qsub.py file to the outer directory of the install and made it user definable (using the 'uga settings' module). You would still need to make the file executable, however.

**Comment by shirley0818** [comment]
Hi Ryan,

As you suggested, I updated uga to 2.0b5. However, after installing, to check whether uga is functional with “uga –h”, I got the following error:  Do I need to remove the old version “2.0b3” before updating? Many thanks, Xiaoling

(uga_python2.7)[zhangxl@scc4 uga-2.0b5]$ uga -h
Traceback (most recent call last):
  File "/usr3/graduate/zhangxl/.conda/envs/uga_python2.7/bin/uga", line 9, in <module>
    load_entry_point('uga==2.0b5', 'console_scripts', 'uga')()
  File "/usr3/graduate/zhangxl/.conda/envs/uga_python2.7/lib/python2.7/site-packages/setuptools-18.5-py2.7.egg/pkg_resources/__init__.py", line 565, in load_entry_point
  File "/usr3/graduate/zhangxl/.conda/envs/uga_python2.7/lib/python2.7/site-packages/setuptools-18.5-py2.7.egg/pkg_resources/__init__.py", line 2697, in load_entry_point
  File "/usr3/graduate/zhangxl/.conda/envs/uga_python2.7/lib/python2.7/site-packages/setuptools-18.5-py2.7.egg/pkg_resources/__init__.py", line 2370, in load
  File "/usr3/graduate/zhangxl/.conda/envs/uga_python2.7/lib/python2.7/site-packages/setuptools-18.5-py2.7.egg/pkg_resources/__init__.py", line 2376, in resolve
  File "/usr3/graduate/zhangxl/.conda/envs/uga_python2.7/lib/python2.7/site-packages/uga-2.0b5-py2.7-linux-x86_64.egg/uga/__main__.py", line 18, in <module>
    import demandimport; demandimport.enable(); demandimport.ignore('bottleneck'); demandimport.ignore('pathlib')
ImportError: No module named demandimport

**Comment by rmkoesterer** [comment]
Hi Xiaoling,

The new version has slightly different requirements. It needs a module named demandimport, which is not part of your existing conda environment. What I usually do is install a new conda environment under the name of the uga release that you are installing. The following commands should install it correctly.
>>> tar -xvf uga-2.0b5.tar.gz
>>> cd uga_v2.0b5
>>> conda env create -f environment.yml
>>> source activate uga_v2.0b5

**Comment by shirley0818** [comment]
Thanks Ryan. By following your suggestion. I successfully installed uga-2.0b5, however, when running “uga snvgroup”, I got the following error. Please help me out. Thanks, Xiaoling

(uga_v2.0b5)[zhangxl@scc4 uga_snvgroup]$ ./high.enriched.sh

uga v2.0b5 (c) 2015 Ryan Koesterer   GNU General Public License v3

   This program is free software: you can redistribute it and/or
   modify it under the terms of the GNU General Public License as
   published by the Free Software Foundation, either version 3 of the
   License, or (at your option) any later version.

   This program is distributed in the hope that it will be useful, but
   WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
   General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with this program.  If not, see
   <http://www.gnu.org/licenses/>


active module: snvgroup

ERROR: uga qsub wrapper /usr3/bustaff/koesterr/uga/Qsub.py is not executable

**Comment by rmkoesterer** [comment]
Hi,
You just need to update the settings using the 'uga settings' module. Enter 'uga settings -h' to get help. The current settings are the ones below. You can see that the 'wrapper' setting is for the file that caused the error, because it does not exist. You just need to update these file locations and you should be ok to run.

snpeff = /restricted/projectnb/addiction/annotation/snpEff/snpEff.jar
snpsift = /restricted/projectnb/addiction/annotation/snpEff/SnpSift.jar
dbnsfp = /restricted/projectnb/addiction/annotation/snpEff/data/dbNSFP_current
locuszoom = /restricted/projectnb/addiction/programs/locuszoom/bin/locuszoom
wrapper = /usr3/bustaff/koesterr/uga/Qsub.py

You need to change the location of Qsub.py to the one in your uga_v2.0b5 directory that you just installed from. Also, make sure that you have set the Qsub.py file as executable.

**Comment by shirley0818** [comment]
Thank you very much. Now I am all set. Really appreciate your help.

I would like to say that the newest version uga_v2.0b5 is better than old versions. It’s great to see that you have been trying to update uga, which is a very very good tool. Thanks again for your response in a timely manner!

Best,
Xiaoling
